// Generated by gencpp from file recognition_msgs/Recognition.msg
// DO NOT EDIT!


#ifndef RECOGNITION_MSGS_MESSAGE_RECOGNITION_H
#define RECOGNITION_MSGS_MESSAGE_RECOGNITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace recognition_msgs
{
template <class ContainerAllocator>
struct Recognition_
{
  typedef Recognition_<ContainerAllocator> Type;

  Recognition_()
    : x(0.0)
    , y(0.0)
    , label()  {
    }
  Recognition_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , label(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;




  typedef boost::shared_ptr< ::recognition_msgs::Recognition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::recognition_msgs::Recognition_<ContainerAllocator> const> ConstPtr;

}; // struct Recognition_

typedef ::recognition_msgs::Recognition_<std::allocator<void> > Recognition;

typedef boost::shared_ptr< ::recognition_msgs::Recognition > RecognitionPtr;
typedef boost::shared_ptr< ::recognition_msgs::Recognition const> RecognitionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::recognition_msgs::Recognition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::recognition_msgs::Recognition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace recognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'recognition_msgs': ['/home/odroid/catkin_ws/src/recognition_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::recognition_msgs::Recognition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::recognition_msgs::Recognition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_msgs::Recognition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_msgs::Recognition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_msgs::Recognition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_msgs::Recognition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::recognition_msgs::Recognition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "758d8c9fcfdf72f4de3bde06357b9c26";
  }

  static const char* value(const ::recognition_msgs::Recognition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x758d8c9fcfdf72f4ULL;
  static const uint64_t static_value2 = 0xde3bde06357b9c26ULL;
};

template<class ContainerAllocator>
struct DataType< ::recognition_msgs::Recognition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "recognition_msgs/Recognition";
  }

  static const char* value(const ::recognition_msgs::Recognition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::recognition_msgs::Recognition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
string label\n\
";
  }

  static const char* value(const ::recognition_msgs::Recognition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::recognition_msgs::Recognition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Recognition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::recognition_msgs::Recognition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::recognition_msgs::Recognition_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECOGNITION_MSGS_MESSAGE_RECOGNITION_H
